This is my first day exploring NumPy formally. I want to discover a way to engage in math through real programming cases.

In [ ]:
import numpy as np

List comprehension trick
Remember that a comprehension is a way to create a data structure (list, set or dictionary) without appending or looping.
It follows this structure:

In [187]:
new_list = [char for char in 'hello']
print(new_list)

['h', 'e', 'l', 'l', 'o']


In [27]:
np.array([range(i, i + 3) for i in [1,2,3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

This comprehension takes each element in [1,2,3] and makes a list starting on it. Then, the function np.array creates an array from the "list of lists".

There are two main types of arrays.
1. 1D-arrays
2. Multidimensional arrays (2D, 3D)

In [49]:
np.random.randint(8, size=6)

array([5, 5, 4, 2, 6, 3])

In [63]:
x1 = np.random.randint(10, size=(3, 4, 5))
x1

array([[[8, 9, 8, 0, 4],
        [7, 4, 0, 2, 2],
        [9, 1, 8, 9, 1],
        [9, 2, 1, 4, 3]],

       [[4, 4, 6, 2, 2],
        [5, 5, 5, 5, 2],
        [9, 6, 7, 3, 4],
        [9, 1, 9, 7, 8]],

       [[0, 3, 5, 0, 8],
        [9, 8, 8, 7, 4],
        [1, 6, 5, 9, 1],
        [2, 5, 2, 2, 5]]])

In [69]:
x1[0,0,0]

8

In [73]:
x1[0,0,0] = 15
x1

array([[[15,  9,  8,  0,  4],
        [ 7,  4,  0,  2,  2],
        [ 9,  1,  8,  9,  1],
        [ 9,  2,  1,  4,  3]],

       [[ 4,  4,  6,  2,  2],
        [ 5,  5,  5,  5,  2],
        [ 9,  6,  7,  3,  4],
        [ 9,  1,  9,  7,  8]],

       [[ 0,  3,  5,  0,  8],
        [ 9,  8,  8,  7,  4],
        [ 1,  6,  5,  9,  1],
        [ 2,  5,  2,  2,  5]]])

In [191]:
y = np.random.randint(10, size = (3,3))
y

array([[1, 0, 9],
       [0, 9, 6],
       [2, 0, 0]])

Introducing the slicing, with the structure:
[start:stop:step]

Default: start=0, stop=size of the array, step=1

In [196]:
y[:1,]

array([[1, 0, 9]])

In [198]:
y[2:3, :2]

array([[2, 0]])

In [200]:
y[1:2,1:]

array([[9, 6]])

In [206]:
y[:, :1]

array([[1],
       [0],
       [2]])

In [208]:
y[1:, :2]

array([[0, 9],
       [2, 0]])

The following gives you the first, second, and third column as a 1D-array

In [215]:
y[:, 0]

array([1, 0, 2])

In [223]:
y[:, 1]

array([0, 9, 0])

In [225]:
y[:,2]

array([9, 6, 0])

In [227]:
print(y)

[[1 0 9]
 [0 9 6]
 [2 0 0]]


You can reshape arrays

In [135]:
z = np.random.randint(10, size = (2,3))
z

array([[6, 2, 4],
       [8, 0, 5]])

In [139]:
z_variation = z.reshape(3,2)
z_variation

array([[6, 2],
       [4, 8],
       [0, 5]])

You can combine arrays. The example bellow combines two 2D-arrays

In [165]:
a = np.random.randint(10, size=(2,2))
b = np.random.randint(10, size=(2,2))

c = np.dstack((a, b))
print(c)

[[[2 5]
  [6 0]]

 [[4 5]
  [9 5]]]


You can split arrays

In [183]:
a = [0,1,2,3,4]
b,c,d = np.split(a, [2,5])
print(b,c,d)

[0 1] [2 3 4] []


You can perform a lot of operations with arrays using ufuncts. These are vectorized operations, which means that if you add 5 to the array, this results in every element of the array plus 5. 

Ex:

In [233]:
array1 = np.array([1,2,3,4,5])

array1_plus_5 = np.add(5, array1)
array1_plus_5_another_way = 5 + array1

print(array1_plus_5)
print(array1_plus_5_another_way)

[ 6  7  8  9 10]
[ 6  7  8  9 10]


You also can perform other arithmetic operations such as substraction, multiplication, division, modulus. Also exponents, logarithms, trig functions, advance functions and more.